addSbtPlugin("com.github.sbt"   % "sbt-github-actions" % "0.24.0")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"       % "0.5.2")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"      % "2.2.0")
addSbtPlugin("org.scoverage"    % "sbt-coveralls"      % "1.3.14")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"        % "0.6.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"       % "0.13.0")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"     % "1.6.1")
